### ISSUE TITLE
Investigate architectural changes for future versions.

### ISSUE THREAD

**Issue by ghost** [ualibraries/patron-groups#14] opened 2019-10-24 17:11 UTC
After discussion with Mark Fischer over at UITS, a couple of things to think about for a v2.0.0 release down the road: redo this as an AWS Lambda serverless function (may or may not work based on 15-minute max residency limit for Lambda processes) which would let us drop the Docker bits; alternatively, AWS Fargate (which I know nothing about other than the name and that Mark said it was worth looking at) might replace the RancherOS-based EC2 hosting with something a little higher-level -- we'd still be building a Docker container, but we'd be dropping that container into AWS's container-management services rather than building our own EC2 instance to run that environment.

**Comment by astrochun** [comment] 2019-12-13 18:15
You might look into the [CloudOps Task-As-A-Service](https://cloudops.arizona.edu/task-service) option.  I believe that is free, but unclear if it has a 15-min timeout issue. Given that it was intended for EDS look-up, I would be surprised if it did.

**Comment by zensense** [comment] 2020-06-24 16:13
Closing this (for now) since we've stripped the Docker out of the repo. Eventually, it'd still be good to do this on AWS somehow, but running a Python package should not depend on Docker.

**Closed as completed by zensense** 2020-06-24 16:13 UTC
